### ISSUE TITLE
Issue on testing shapenet segmentation

### ISSUE THREAD

**Issue by Salingo** [yangyanli/PointCNN#69] opened 2018-09-18 02:38 UTC
Hello,
When I'm trying to test segmentation following the instructions `./test_shapenet.sh -g 0 -x shapenet_x8_2048_fps -l ../../models/seg/pointcnn_seg_shapenet_x8_2048_fps_xxxx/ckpts/iter-xxxxx -r 10`, I get an error as shown below:
```
2018-09-18 10:18:34.117660-Checkpoint loaded from ../../models/seg/pointcnn_seg_shapenet_x8_2048_fps_2018-09-14-20-14-53_33611/ckpts/iter-120000!
2018-09-18 10:18:37.421180-[Testing]-Iter: 000000 saved to ../../data/shapenet_partseg/test_data_pred_nips_10/02691156/014009.seg
Traceback (most recent call last):
  File "../test_shapenet_seg.py", line 157, in <module>
    main()
  File "../test_shapenet_seg.py", line 110, in main
    object_label = label[batch_idx]
IndexError: invalid index to scalar variable.
```
I didn't modify the test file, so is this a bug?
Thanks very much!

**Comment by burui11087** [comment] 2018-09-18 08:57
Hi @Salingo 

I have fixed this bug, you can just update you test_shapenet_seg.py file. It caused by variable "label" was assigned a new value.

I will close this issue.Please feel free to reopen it if you have other problems.

**Closed by burui11087** 2018-09-18 08:57 UTC

**Comment by Salingo** [comment] 2018-09-18 15:42
@burui11087 Thanks very much!
