### ISSUE TITLE
about folder split_data

### ISSUE THREAD

**Issue by What-ifs** [yangyanli/PointCNN#81] opened 2018-10-05 07:58 UTC
Thank you for your outstanding contribution! I've been working on 3D point clouds recently, but I found that there is no folder split_data, I would appreciate it very much if you could provide it. Or maybe you fogot update the file READEME.md(data_conversions/)? If it is, did some data path error is there between those data prepare files?

**Comment by MingChaoSun** [comment] 2018-10-08 02:30
Hi @What-ifs 

I think [issues#76](https://github.com/yangyanli/PointCNN/issues/76) may help you～

Thanks

**Comment by burui11087** [comment] 2018-10-08 02:35
Hi @What-ifs 

README.md has been updated sevral months ago. I recommend you pull code again.

Thanks

**Comment by burui11087** [comment] 2018-10-08 02:35
Duplicate of #76

**Comment by What-ifs** [comment] 2018-10-08 02:41
@yangyanli Thank you for your serious reply, but I found that if the file README.md(data_conversions/) has not been updated?

**Comment by burui11087** [comment] 2018-10-08 02:59
@What-ifs 

Hi, We have deleted verbose information in data_conversions/README.md. Thanks for your reminding.

**Closed** 2018-10-08 02:59 UTC
