### ISSUE TITLE
Undefined name 'tnet'

### ISSUE THREAD

**Issue by cclauss** [yangyanli/PointCNN#2] opened 2018-01-25 16:26 UTC
https://github.com/yangyanli/PointCNN/blob/master/pointnetpp_cls/utils/pointnet_util.py#L49

flake8 testing of https://github.com/yangyanli/PointCNN

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./pointnetpp_cls/utils/pointnet_util.py:49:23: F821 undefined name 'tnet'
        grouped_xyz = tnet(grouped_xyz, tnet_spec)
                      ^
1     F821 undefined name 'tnet'
```

**Comment by burui11087** [comment] 2018-01-26 08:09
I also get this output by use
`$ flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics`
but this information is not fatal and code can run fine.
BTW,you can see the source code by this link[https://github.com/charlesq34/pointnet2](url),
Thanks

**Comment by cclauss** [comment] 2018-01-26 08:31
Did you try to call __sample_and_group()__ with a __tnet_spec__ parameter that is not None?

**Comment by burui11087** [comment] 2018-01-27 04:52
haven't

**Comment by cclauss** [comment] 2018-01-27 06:26
What flake8 is telling you is that if __sample_and_group()__ is called with a __tnet_spec__ parameter that is not None then NameError might be raised at runtime.

**Comment by yangyanli** [comment] 2018-01-27 11:53
Hi @cclauss,

Many thanks for reporting this potential problem detected by flake8. The problem is from PointNet++. We adopted it into our framework for making comparisons with it. However, we didn't test all the configurations of it, and we do not plan to do so in the near future.

In the near future, we plan to improve our documentation, as well as smooth out the scripts for running PointCNN on ScanNet, S3DIS, etc.

For your problem, we guess it would be better if it can be reported to PointNet++. How do you think about it?

**Comment by yangyanli** [comment] 2018-01-27 22:49
I am going to close this issue, as it is PointNet++ related, and had been reported to it.

**Closed by yangyanli** 2018-01-27 22:49 UTC
