### ISSUE TITLE
I found some bugs!!

### ISSUE THREAD

**Issue by luoxiaoliaolan** [yangyanli/PointCNN#38] opened 2018-05-10 12:58 UTC
Recently I studied the semantic segmentation of point cloud data.  I mainly process point clouds in outdoor scenes. I found that this repo has been changed very frequently. When I run test_s3dis.sh in S3DIS, I found some errors:
1. In your README.md, 162 line, "./test_s3dis.sh -g 0 -x s3dis_x8_2048_fps_k16 -l ../../models/seg/s3dis_x8_2048_fps_k16_xxxx/ckpts/iter-xxxxx -r 4", I notice the "s3dis_x8_2048_fps_k16" is wrong, because in "pointcnn_seg" folder, there is "s3dis_x8_2048_k16_fps" 
2. In test_s3dis.sh, 68 line, "CUDA_VISIBLE_DEVICES=$gpu python3 ../test_geneal_seg.py -t ../../data/S3DIS/out_part_rgb/val1.txt -f ../../data/S3DIS/out_part_rgb/Area1_data/ -c ../../data/S3DIS/out_part_rgb/categories.txt -l $ckpt -m pointcnn_seg -x $setting -r $repeat $save_ply"
“test_geneal_seg.py” miss "r" in "general"
3. In "test_general_seg.py", 91 line, "net = model.Net(points_sampled, features_sampled, num_class, is_training, setting)" a parameter "num_class" is may be redundant， because in pointcnn_seg.py, 10 line,  " def __init__(self, points, features, is_training, setting):"  without "num_class" parameter.
 I also found some other errors in the process of running……
I would like to ask a few questions:
1. In "#pointcnn-master#/data_conversions/split_data/s3dis_split.py" , Can you describe the idea of dividing point cloud data into space volexs for quantitative statistics? And why do you want to downsampling? Can the final test result restore the original point cloud number?
I'm running point cloud data on servers in our lab and I hope to keep in touch with your team.
My e-mail: lybluoxiao@qq.com

**Comment by yangyanli** [comment] 2018-05-12 15:41
Good catch for 1 and 2!

For 3, it is a duplicate of #36.

For 4, we will add more details on how the segmentation data is processed after NIPS deadline.

**Closed by yangyanli** 2018-05-12 15:41 UTC
